#!/bin/sh
# docker-entrypoint.sh
# Generates config.js from environment variables before starting nginx.
# Required env vars:
#   AUTH0_DOMAIN    – e.g. your-tenant.auth0.com
#   AUTH0_CLIENT_ID – the Auth0 Application client ID
set -e

cat > /usr/share/nginx/html/config.js << EOF
// Auto-generated by docker-entrypoint.sh – do not edit manually.
window.AUTH0_CONFIG = {
  domain: "${AUTH0_DOMAIN}",
  clientId: "${AUTH0_CLIENT_ID}"
};
EOF

exec "$@"
